name = "vic-events-router"
main = "worker.js"
compatibility_date = "2026-03-14"

routes = [
	{ pattern = "vic.college/*", zone_name = "vic.college" },
	{ pattern = "www.vic.college/*", zone_name = "vic.college" }
]

[vars]
# Replace after you deploy.
HIEVENTS_ORIGIN = "https://vidya-innovation-centre-production.up.railway.app"
LANDING_ORIGIN = "https://vic.college"
